[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bddap-aoc = { version = "0.1.1", path = "../../bddap-aoc/bddap-aoc" }
linkme = "0.3.17"
